# Generated by Django 4.2.15 on 2024-10-22 04:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('content', models.TextField(verbose_name="Contenu de l'étape")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influenceur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=30, verbose_name='Instagram ID')),
                ('instagram_username', models.CharField(max_length=30, verbose_name='Instagram username')),
                ('biographie', models.TextField(verbose_name='Bio')),
                ('photo_profil', models.ImageField(null=True, upload_to='profils/')),
                ('nb_followers', models.IntegerField(verbose_name='Nombre de followers')),
                ('nb_recettes', models.IntegerField(verbose_name='Nombre de recettes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_singulier', models.CharField(max_length=30)),
                ('nom_pluriel', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=30, verbose_name='Quantité')),
                ('unite_mesure', models.CharField(max_length=30, verbose_name='')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('nb_vue', models.IntegerField(verbose_name='Nombre de vues')),
                ('photo', models.ImageField(upload_to='recettes/')),
                ('nb_personnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('etapes', models.ManyToManyField(to='application.etape', verbose_name='Etapes')),
                ('influenceur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.influenceur')),
                ('quantites', models.ManyToManyField(to='application.quantite', verbose_name='Quantités')),
                ('tags', models.ManyToManyField(to='application.tag', verbose_name='tags')),
            ],
        ),
    ]
