# Generated by Django 4.2.15 on 2024-10-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_recette_influenceur_remove_recette_nb_vue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
