# Generated by Django 4.2.15 on 2024-10-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recette', to='application.video', verbose_name='Vidéo'),
        ),
    ]
