# Generated by Django 4.2.15 on 2024-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_thumbnail_video_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='nom',
        ),
        migrations.AlterField(
            model_name='video',
            name='nb_likes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de likes'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nb_vue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='videos'),
        ),
    ]
